**Problem:**

You are given the following dataset:
1. **Audible Data** : https://1drv.ms/u/s!AiqdXCxPTydhoog8ckLN-6Cw55fzIg?e=EWgZ5d

Your task is to:
- Find the problems with the datasets.
- Define the Data Quality Dimensions.
- Try to clean the datasets.

## Problem with the dataset:
- `name`: 
    - Some books has the version in different formats.
        - [x] with hast-tag like "Geronimo Stilton #11 & #12".
        - [x] "Magic Tree House Collection: Books 9-16".
        - [x] "The 39 Clues, Book 6"
    - â€™, Ã¤, Ã¼ values
        - [x] Some rows (9, 34, 157, 162, 170...) have this strange part.


- `author` & `narrator`:
    - [x] Every value starts with "Writtenby:" e.g., "Writtenby:GeronimoStilton"
    - [x] Some values represent 2 or more authors, e.g., "Writtenby:JuliaDonaldson,AxelScheffler"
    - [x] Some values also have the strange part, e.g., "Writtenby:FranciscoDÃ­azValladares"
    - [x] First name and the last are not separated with a white space, e.g. "Writtenby:NicolasGorny".
    - [x] Some additional informations are also inclused in some values. E.g., "Writtenby:AndrewPeterson-editor,JonathanRogers,N.D.Wilson,"
    - [x] There are no proper names in narrator, e.g., "Narratedby:uncredited".


- `time`:
    - [x] The values are combination of total hour and minutes, e.g., "2 hrs and 20 mins", "10 hrs", "22 mins"


- `releasedate`:
    - [x] There are 2 types entries, "08-04-2008" and "13-01-10"
    - [x] The dtype is object, if we convert to datetime object, then the above will be resolved.


- `language`
    - [x] Some values are in title formed and some are in lower case, e.g. "English" and "german".


- `stars`
    - [x] Total ratings informations are included along with average stars, e.g. "5 out of 5 stars34 ratings"
    - [x] The highest rating is 5 and lower is 1. How many avg. stargs got a book is included as long form.
    - [x] Some empty values are represented as "Not rated yet". For that, we can assume total ratings = 0 and avg. ratings = 0.


- `price`
    - [x] There is a value, "Free". This also change the dtype of the column.

In [81]:
import numpy as np
import pandas as pd

import re

In [131]:
import zipfile
import pandas as pd

## print(z.namelist())  # Check which files are inside
with zipfile.ZipFile('audible_uncleaned.csv.zip') as z:
    with z.open('audible_uncleaned.csv') as f:
        df = pd.read_csv(f)
df
df.to_excel('audible_uncleaned.xlsx', index=False)  # index=False avoids writing row numbers
print("Data has been saved as audible_uncleaned.xlsx")

PermissionError: [Errno 13] Permission denied: 'audible_uncleaned.xlsx'

In [132]:
df.head(2)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00

In [133]:
df.info()
#not any null value that iis good thing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

In [134]:
df[df.duplicated(subset=['name'])].to_excel('duplicates.xlsx', index=False)

In [135]:
ef=df[df.duplicated(subset=['name'])]


pd.DataFrame(df[df.duplicated(subset=['name'])].groupby('name'))

,0,1
0,"""Das Böse ist des Menschen beste Kraft""",name...
1,#Girlboss,name author ...
2,100 quotes by Benjamin Franklin,name ...
3,101 Amazing Facts About Jane Austen,name \ ...
4,12 anni schiavo,name auth...
...,...,...
3225,羅生門,name author narrator ...
3226,自律神経を整える「月と太陽」の呼吸法,name author ...
3227,芋虫,name author narrator ...
3228,途上,name author narrator ...
3229,雨ニモマケズ,name author narrator...

In [136]:
df[df['stars']=='Not rated yet']
#too manyy movies are not rated

,name,author,narrator,time,releasedate,language,stars,price
34,"14 Short Stories Bundle for Kids: Adventure, S...",Writtenby:NayomiPhillips,"Narratedby:MonicaRachelle,JimD.Johnston,KatieO...",3 hrs and 13 mins,22-01-19,English,Not rated yet,501.00
50,A Bear Called Paddington,Writtenby:MichaelBond,Narratedby:StephenFry,2 hrs and 39 mins,24-06-08,English,Not rated yet,266.00
51,Gregor and the Curse of the Warmbloods,Writtenby:SuzanneCollins,Narratedby:PaulBoehmer,7 hrs and 47 mins,26-12-04,English,Not rated yet,"1,005.00"
61,Across the Desert,Writtenby:DustiBowling,Narratedby:StacyGonzalez,6 hrs and 13 mins,29-03-22,English,Not rated yet,703.00
62,Unicorn Academy: Aisha and Silver,Writtenby:JulieSykes,Narratedby:KristinAtherton,1 hr and 34 mins,10-03-22,English,Not rated yet,266.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [113]:
df.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

In [137]:
# convert the "releasedate" col to datetime object
df["releasedate"] = pd.to_datetime(df["releasedate"]).copy()
# remove the value "free" from the col price. This will automatically
# convert to the float values.
df["price"] = df["price"].replace("Free", 0)
df["price"] = df["price"].astype(str).str.replace(",", "")
df["price"] = df["price"].astype(float)

C:\Users\Soham\AppData\Local\Temp\ipykernel_21716\3943065771.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["releasedate"] = pd.to_datetime(df["releasedate"]).copy()

In [115]:
# now check again the dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  datetime64[ns]
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 5.3+ MB

In [138]:
def find_total_ratings(text):
    # if NaN, then return as it dis
    if pd.isna(text):
        return text
    
    # create the pattern to find the total ratings
    tol_rattings_pattern = re.compile(r"[\d]+\sratings")
    # get the result
    result = re.findall(tol_rattings_pattern, text)

    try:
        # if we find the total ratings, then convert to int and return it
        if len(result) > 0:
            return int(result[0].split(" ")[0])
        # if it is the "Not rated yet", return 0
        elif "Not rated yet":
            return 0
        # else return the value as it is
        else:
            return text
    # if we got any error, also return the value as it is
    except Exception as e:
        print(e)
        return text

In [139]:
# find out the total counted ratings
df["total_ratings"] = df["stars"].apply(lambda x: find_total_ratings(x))
df["avg_stars"]     = df["stars"].apply(lambda x: float(x.split(" ")[0]) if x != "Not rated yet" else 0)
# now drop the "stars" column
df = df.drop(columns = ["stars"]).copy()

In [140]:
df['time']

0         2 hrs and 20 mins
1         13 hrs and 8 mins
2          2 hrs and 3 mins
3        11 hrs and 16 mins
4                    10 hrs
                ...
87484     7 hrs and 34 mins
87485     10 hrs and 7 mins
87486     19 hrs and 4 mins
87487      4 hrs and 8 mins
87488       6 hrs and 1 min
Name: time, Length: 87489, dtype: object

In [141]:
# convert the "language" col to titlecase
df["language"] = df["language"].str.title().copy()

In [142]:
def time(t):
    if pd.isna(t):
        return t

    original = t.strip()
    t = original.replace("mins", "min").replace("min", "")
    t = t.replace("hrs", "hr").replace("hr", "")
    t = t.replace("and", "")
    parts = t.split()

    if len(parts) == 2:
        # both hours and minutes present
        return int(parts[0]) * 60 + int(parts[1])
    elif len(parts) == 1:
        num = int(parts[0])
        # detect if it's hours or minutes by original text
        if "hr" in original or "hrs" in original:
            return num * 60
        else:
            return num  # assume it's minutes
    else:
        return 0  # invalid or empty input

In [143]:
df["time"] = df["time"].apply(lambda x: time(x))

In [144]:
df['time']

0         140
1         788
2         123
3         676
4         600
         ...
87484     454
87485     607
87486    1144
87487     248
87488     361
Name: time, Length: 87489, dtype: int64